spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rendoc  # replace mydatabase with your DB name
    username: postgres                                 # your DB username
    password: root                             # your DB password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: update      # options: none, validate, update, create, create-drop
    show-sql: true           # logs SQL statements
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Optional: configure server port
server:
  port: 8081

# Optional: logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
